### ISSUE TITLE
Savings fails 

### ISSUE THREAD

**Issue by gberche-orange** [JohnMcLear/ep_set_title_on_pad#10]
Using our etherpad 1.5.7 running on [cloudfoundry](https://github.com/cloudfoundry-community/etherpad-lite-cf), the saving of the title fails: it is not persistent the the pad gets reloaded.

I see the following stdout output when saving

```
[WARN] message -Dropped message, unknown COLLABROOM Data  Type title
```

I tried checking whether the issue could come from our private etherpad-lite installation by whether checking [public instances](https://github.com/ether/etherpad-lite/wiki/Sites-that-run-Etherpad-Lite) have this plugin, did not find one yet. Any chance to turn it on into https://beta.etherpad.org/ ?

I also yet have to try to disable all other plugins and check whether this could be a side effect of another plugin. Looking at the client-side JS console, I see some polutting ep_tables2 related traces, but none seems obviously related to ep_set_title_on_pad

I'd appreciate if anyone had guidance on whether this problem could be related to my installation, or whether the ep_set_title_on_pad plugin could be currently broken, and if so ways to fix it.

**Comment by gberche-orange** [comment]
I tried looking into the code for potential root cause, but I'm not yet that much familiar with etherpad-lite internals, so I might be way out.

Trying to understand the message: 

```
2015-10-02T12:05:58.07+0200 [App/0]      OUT [2015-10-02 12:05:58.074] [WARN] message -Dropped message, unknown COLLABROOM Data  Type title
```

I'm guessing that the plugin sent a COLLABROOM message of type title that was properly received by the server, but this message type was unsupported. Is it because the plugin was lacking a data type registration step? 

Tried to find out more about collabroom in the doc. Found the following so far:
* http://blog.etherpad.org/2014/12/15/etherpad-1-4-plugin-upgrade/ but could not relate it to [send title message](https://github.com/JohnMcLear/ep_set_title_on_pad/blob/7be1ff19b69b18b1010f25843c235d275f421f4f/static/js/index.js#L73)

Related to message handling the following seemed relevant
* http://etherpad.org/doc/v1.5.7/#index_handleclientmessage_name
* http://etherpad.org/doc/v1.5.7/#index_handlemessage

Thanks in advance for help on this.

**Comment by JohnMcLear** [comment]
I'm unable to replicate..

STNR:

1. Bring up new Etherpad instance (latest commit of develop)
1. git clone this plugin into node_modules folder
1. Create new pad
1. Set title to "derp"
1. Refresh page.

Title is "derp"

**Comment by gberche-orange** [comment]
Thanks @JohnMcLear for your testing and your help. 
I'll now test with only this plugin, and double check any side effect from running within cloudfoundry.

**Comment by gberche-orange** [comment]
The issue was when running within cloudfoundry (more details of the fix in https://github.com/cloudfoundry-community/etherpad-lite-cf/commit/6f1d45760d31ac5fafdb399212b6ceaea2fe02bc ). 

Sorry for the unrelated noise in this issue and thanks again for your help.
