### ISSUE TITLE
Popups should be moved down

### ISSUE THREAD

**Issue by rugk** [JohnMcLear/ep_set_title_on_pad#13]
Currently it looks like this:
![importexport](https://cloud.githubusercontent.com/assets/11966684/15263252/a50cafee-1968-11e6-895b-704814bcf01d.png)

**Comment by JohnMcLear** [comment]
The problem is that "skins" are now introduced so even if I fixed in plugin it might mess up styling for each skin so I can't really fix this in the plugin! :(
