### ISSUE TITLE
Use the CSS from the theme

### ISSUE THREAD

**Issue by JohnMcLear** [JohnMcLear/ep_set_title_on_pad#20]
http://video.etherpad.com/p/sdlkjflksjdlksjfd#skinvariantsbuilder

When you change tihngs to dark the title bar should follow suite.

@seballot

**Comment by JohnMcLear** [comment]
@seballot what did we decide on this? :)

**Comment by seballot** [comment]
woups, I already fixed it, but badly ! I made a proper fix here https://github.com/ether/etherpad-lite/pull/4017

**Comment by JohnMcLear** [comment]
Okies ta :)
